# Generated by Django 4.2.16 on 2024-10-16 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelplan",
            name="users",
            field=models.ManyToManyField(
                related_name="group_codes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="travelplan",
            name="primary_group_code",
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name="GroupCode",
        ),
    ]
