# Generated by Django 4.2.16 on 2024-11-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="destination",
            name="location_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="destination",
            name="location_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="destination",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
