# Generated by Django 4.2.16 on 2024-10-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_travelplan_users_alter_travelplan_primary_group_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelplan",
            name="primary_group_code",
            field=models.CharField(max_length=100),
        ),
    ]
