# Generated by Django 4.2.16 on 2024-11-17 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_travelplan_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelplan",
            name="jpg_metadata",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jpg_travel_plan",
                to="users.filemetadata",
            ),
        ),
        migrations.AddField(
            model_name="travelplan",
            name="pdf_metadata",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pdf_travel_plan",
                to="users.filemetadata",
            ),
        ),
        migrations.AddField(
            model_name="travelplan",
            name="txt_metadata",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="txt_travel_plan",
                to="users.filemetadata",
            ),
        ),
    ]
