# Generated by Django 4.2.16 on 2024-11-17 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_travelplan_jpg_metadata_travelplan_pdf_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="jpg_metadata",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jpg_destination",
                to="users.filemetadata",
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="pdf_metadata",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pdf_destination",
                to="users.filemetadata",
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="txt_metadata",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="txt_destination",
                to="users.filemetadata",
            ),
        ),
    ]
