# Generated by Django 4.2.16 on 2024-10-19 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_travelplan_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplan',
            name='plan_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
