# Generated by Django 4.2.16 on 2024-10-31 03:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_travelplan_jpg_upload_file_subplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('destination_description', models.TextField()),
                ('jpg_upload_file', models.FileField(blank=True, null=True, upload_to='uploads/destinations_jpgs/')),
                ('txt_upload_file', models.FileField(blank=True, null=True, upload_to='uploads/destinations_txts/')),
                ('pdf_upload_file', models.FileField(blank=True, null=True, upload_to='uploads/destination_pdfs/')),
            ],
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='pdf_upload_file',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='txt_upload_file',
        ),
        migrations.DeleteModel(
            name='SubPlan',
        ),
        migrations.AddField(
            model_name='destination',
            name='travel_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='users.travelplan'),
        ),
    ]
